apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy1
  name: deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy1
    spec:
      containers:
      - image: chiragshripat/java-pipeline:latest
        name: java-app

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy1
  name: deploy1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy1
  type: NodePort
